In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
travel = pd.read_csv("Traveldata_train.csv");
survey = pd.read_csv("Surveydata_train.csv");

In [3]:
travel.head()

ID  Gender    CustomerType   Age       TypeTravel Travel_Class  \
0  2100001  Female  Loyal Customer  52.0              NaN     Business   
1  2100002    Male  Loyal Customer  48.0  Personal Travel          Eco   
2  2100003  Female  Loyal Customer  43.0  Business travel     Business   
3  2100004  Female  Loyal Customer  44.0  Business travel     Business   
4  2100005  Female  Loyal Customer  50.0  Business travel     Business   

   Travel_Distance  DepartureDelay_in_Mins  ArrivalDelay_in_Mins  
0              272                     0.0                   5.0  
1             2200                     9.0                   0.0  
2             1061                    77.0                 119.0  
3              780                    13.0                  18.0  
4             1981                     0.0                   0.0

In [4]:
shinkansen = pd.merge(travel,survey,on='ID')

In [5]:
shinkansen.head()

ID  Gender    CustomerType   Age       TypeTravel Travel_Class  \
0  2100001  Female  Loyal Customer  52.0              NaN     Business   
1  2100002    Male  Loyal Customer  48.0  Personal Travel          Eco   
2  2100003  Female  Loyal Customer  43.0  Business travel     Business   
3  2100004  Female  Loyal Customer  44.0  Business travel     Business   
4  2100005  Female  Loyal Customer  50.0  Business travel     Business   

   Travel_Distance  DepartureDelay_in_Mins  ArrivalDelay_in_Mins  \
0              272                     0.0                   5.0   
1             2200                     9.0                   0.0   
2             1061                    77.0                 119.0   
3              780                    13.0                  18.0   
4             1981                     0.0                   0.0   

   Overall_Experience  ... Onboardwifi_service Onboard_entertainment  \
0                   0  ...                good      need improvement   
1                   0  ...                good                  poor   
2                   1  ...    need improvement                  good   
3                   0  ...          acceptable      need improvement   
4                   1  ...    need improvement                  good   

  Online_support Onlinebooking_Ease   Onboard_service          Leg_room  \
0     acceptable   need improvement  need improvement        acceptable   
1           good               good         excellent  need improvement   
2      excellent          excellent         excellent         excellent   
3     acceptable         acceptable        acceptable        acceptable   
4      excellent               good              good              good   

   Baggage_handling   Checkin_service       Cleanliness Online_boarding  
0  need improvement              good  need improvement            poor  
1              poor  need improvement              good            good  
2         excellent              good         excellent       excellent  
3        acceptable              good        acceptable      acceptable  
4              good              good              good            good  

[5 rows x 25 columns]

In [6]:
shinkansen.isnull().sum()

ID                            0
Gender                       77
CustomerType               8951
Age                          33
TypeTravel                 9226
Travel_Class                  0
Travel_Distance               0
DepartureDelay_in_Mins       57
ArrivalDelay_in_Mins        357
Overall_Experience            0
Seat_comfort                 61
Seat_Class                    0
Arrival_time_convenient    8930
Catering                   8741
Platform_location            30
Onboardwifi_service          30
Onboard_entertainment        18
Online_support               91
Onlinebooking_Ease           73
Onboard_service            7601
Leg_room                     90
Baggage_handling            142
Checkin_service              77
Cleanliness                   6
Online_boarding               6
dtype: int64

In [7]:
shinkansen.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 94379 entries, 0 to 94378
Data columns (total 25 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   ID                       94379 non-null  int64  
 1   Gender                   94302 non-null  object 
 2   CustomerType             85428 non-null  object 
 3   Age                      94346 non-null  float64
 4   TypeTravel               85153 non-null  object 
 5   Travel_Class             94379 non-null  object 
 6   Travel_Distance          94379 non-null  int64  
 7   DepartureDelay_in_Mins   94322 non-null  float64
 8   ArrivalDelay_in_Mins     94022 non-null  float64
 9   Overall_Experience       94379 non-null  int64  
 10  Seat_comfort             94318 non-null  object 
 11  Seat_Class               94379 non-null  object 
 12  Arrival_time_convenient  85449 non-null  object 
 13  Catering                 85638 non-null  object 
 14  Platform_location     

In [8]:
df2= shinkansen.copy()

In [9]:
df2['Gender'].fillna(str(df2['Gender'].mode()),inplace=True)
df2['CustomerType'].fillna(str(df2['CustomerType'].mode()),inplace=True)
df2['TypeTravel'].fillna(str(df2['TypeTravel'].mode()),inplace=True)
df2['Seat_comfort'].fillna(str(df2['Seat_comfort'].mode()),inplace=True)
df2['Arrival_time_convenient'].fillna(str(df2['Arrival_time_convenient'].mode()),inplace=True)
df2['Catering'].fillna(str(df2['Catering'].mode()),inplace=True)
df2['Platform_location'].fillna(str(df2['Platform_location'].mode()),inplace=True)
df2['Onboardwifi_service'].fillna(str(df2['Onboardwifi_service'].mode()),inplace=True)
df2['Onboard_entertainment'].fillna(str(df2['Onboard_entertainment'].mode()),inplace=True)
df2['Online_support'].fillna(str(df2['Online_support'].mode()),inplace=True)
df2['Onlinebooking_Ease'].fillna(str(df2['Onlinebooking_Ease'].mode()),inplace=True)
df2['Onboard_service'].fillna(str(df2['Onboard_service'].mode()),inplace=True)
df2['Leg_room'].fillna(str(df2['Leg_room'].mode()),inplace=True)
df2['Baggage_handling'].fillna(str(df2['Baggage_handling'].mode()),inplace=True)
df2['Checkin_service'].fillna(str(df2['Checkin_service'].mode()),inplace=True)
df2['Cleanliness'].fillna(str(df2['Cleanliness'].mode()),inplace=True)
df2['Online_boarding'].fillna(str(df2['Online_boarding'].mode()),inplace=True)

In [10]:
df2['Age'].fillna(df2['Age'].mean(),inplace=True)
df2['DepartureDelay_in_Mins'].fillna(df2['DepartureDelay_in_Mins'].mean(),inplace=True)
df2['ArrivalDelay_in_Mins'].fillna(df2['ArrivalDelay_in_Mins'].mean(),inplace=True)

In [11]:
df2.isnull().sum()

ID                         0
Gender                     0
CustomerType               0
Age                        0
TypeTravel                 0
Travel_Class               0
Travel_Distance            0
DepartureDelay_in_Mins     0
ArrivalDelay_in_Mins       0
Overall_Experience         0
Seat_comfort               0
Seat_Class                 0
Arrival_time_convenient    0
Catering                   0
Platform_location          0
Onboardwifi_service        0
Onboard_entertainment      0
Online_support             0
Onlinebooking_Ease         0
Onboard_service            0
Leg_room                   0
Baggage_handling           0
Checkin_service            0
Cleanliness                0
Online_boarding            0
dtype: int64

In [12]:
for feature in df2.columns: 
    if df2[feature].dtype == 'object': 
        print('\n')
        print('feature:',feature)
        print(pd.Categorical(df2[feature].unique()))
        print(pd.Categorical(df2[feature].unique()).codes)
        df2[feature] = pd.Categorical(df2[feature]).codes



feature: Gender
[Female, Male, 0    Female\ndtype: object]
Categories (3, object): [0    Female\ndtype: object, Female, Male]
[1 2 0]


feature: CustomerType
[Loyal Customer, disloyal Customer, 0    Loyal Customer\ndtype: object]
Categories (3, object): [0    Loyal Customer\ndtype: object, Loyal Customer, disloyal Customer]
[1 2 0]


feature: TypeTravel
[0    Business travel\ndtype: object, Personal Travel, Business travel]
Categories (3, object): [0    Business travel\ndtype: object, Business travel, Personal Travel]
[0 2 1]


feature: Travel_Class
[Business, Eco]
Categories (2, object): [Business, Eco]
[0 1]


feature: Seat_comfort
[need improvement, poor, acceptable, good, excellent, extremely poor, 0    acceptable\ndtype: object]
Categories (7, object): [0    acceptable\ndtype: object, acceptable, excellent, extremely poor, good, need improvement, poor]
[5 6 1 4 2 3 0]


feature: Seat_Class
[Green Car, Ordinary]
Categories (2, object): [Green Car, Ordinary]
[0 1]


feature: Arriv

In [13]:
df2.head()

ID  Gender  CustomerType   Age  TypeTravel  Travel_Class  \
0  2100001       1             1  52.0           0             0   
1  2100002       2             1  48.0           2             1   
2  2100003       1             1  43.0           1             0   
3  2100004       1             1  44.0           1             0   
4  2100005       1             1  50.0           1             0   

   Travel_Distance  DepartureDelay_in_Mins  ArrivalDelay_in_Mins  \
0              272                     0.0                   5.0   
1             2200                     9.0                   0.0   
2             1061                    77.0                 119.0   
3              780                    13.0                  18.0   
4             1981                     0.0                   0.0   

   Overall_Experience  ...  Onboardwifi_service  Onboard_entertainment  \
0                   0  ...                    4                      5   
1                   0  ...                    4                      6   
2                   1  ...                    5                      4   
3                   0  ...                    1                      5   
4                   1  ...                    5                      4   

   Online_support  Onlinebooking_Ease  Onboard_service  Leg_room  \
0               1                   5                5         1   
1               4                   4                2         5   
2               2                   2                2         2   
3               1                   1                1         1   
4               2                   4                4         4   

   Baggage_handling  Checkin_service  Cleanliness  Online_boarding  
0                 4                4            5                6  
1                 5                5            4                4  
2                 2                4            2                2  
3                 1                4            1                1  
4                 3                4            4                4  

[5 rows x 25 columns]

In [14]:
from scipy.stats import zscore

In [15]:
xtrain = df2.drop(['ID','Overall_Experience'], axis =1)
ytrain = df2['Overall_Experience']

In [16]:
ytrain.value_counts(1)

1    0.546658
0    0.453342
Name: Overall_Experience, dtype: float64

In [17]:
xtrain=xtrain.apply(zscore)

In [ ]:
from sklearn.model_selection import train_test_split,GridSearchCV
from sklearn.linear_model import LogisticRegression
from sklearn import metrics
from sklearn.metrics import roc_auc_score,roc_curve,classification_report,confusion_matrix,plot_confusion_matrix

In [ ]:
model3 = LogisticRegression(solver='newton-cg',max_iter=10000,penalty='none',verbose=True,n_jobs=2)
model3.fit(xtrain, ytrain)

In [18]:
travel1 = pd.read_csv("Traveldata_test.csv");
survey1 = pd.read_csv("Surveydata_test.csv");
shinkansen_test = pd.merge(travel1,survey1,on='ID')
df3 = shinkansen_test.copy()

In [19]:
df3.isnull().sum()

ID                            0
Gender                       30
CustomerType               3383
Age                          11
TypeTravel                 3448
Travel_Class                  0
Travel_Distance               0
DepartureDelay_in_Mins       29
ArrivalDelay_in_Mins        123
Seat_comfort                 22
Seat_Class                    0
Arrival_time_convenient    3325
Catering                   3357
Platform_location            12
Onboardwifi_service          12
Onboard_entertainment         8
Online_support               26
Onlinebooking_Ease           18
Onboard_service            2872
Leg_room                     25
Baggage_handling             40
Checkin_service              22
Cleanliness                   2
Online_boarding               2
dtype: int64

In [20]:
df3['Gender'].fillna(str(df3['Gender'].mode()),inplace=True)
df3['CustomerType'].fillna(str(df3['CustomerType'].mode()),inplace=True)
df3['TypeTravel'].fillna(str(df3['TypeTravel'].mode()),inplace=True)
df3['Seat_comfort'].fillna(str(df3['Seat_comfort'].mode()),inplace=True)
df3['Arrival_time_convenient'].fillna(str(df3['Arrival_time_convenient'].mode()),inplace=True)
df3['Catering'].fillna(str(df3['Catering'].mode()),inplace=True)
df3['Platform_location'].fillna(str(df3['Platform_location'].mode()),inplace=True)
df3['Onboardwifi_service'].fillna(str(df3['Onboardwifi_service'].mode()),inplace=True)
df3['Onboard_entertainment'].fillna(str(df3['Onboard_entertainment'].mode()),inplace=True)
df3['Online_support'].fillna(str(df3['Online_support'].mode()),inplace=True)
df3['Onlinebooking_Ease'].fillna(str(df3['Onlinebooking_Ease'].mode()),inplace=True)
df3['Onboard_service'].fillna(str(df3['Onboard_service'].mode()),inplace=True)
df3['Leg_room'].fillna(str(df3['Leg_room'].mode()),inplace=True)
df3['Baggage_handling'].fillna(str(df3['Baggage_handling'].mode()),inplace=True)
df3['Checkin_service'].fillna(str(df3['Checkin_service'].mode()),inplace=True)
df3['Cleanliness'].fillna(str(df3['Cleanliness'].mode()),inplace=True)
df3['Online_boarding'].fillna(str(df3['Online_boarding'].mode()),inplace=True)

In [21]:
df3['Age'].fillna(df3['Age'].mean(),inplace=True)
df3['DepartureDelay_in_Mins'].fillna(df3['DepartureDelay_in_Mins'].mean(),inplace=True)
df3['ArrivalDelay_in_Mins'].fillna(df3['ArrivalDelay_in_Mins'].mean(),inplace=True)

In [22]:
df3.isnull().sum()

ID                         0
Gender                     0
CustomerType               0
Age                        0
TypeTravel                 0
Travel_Class               0
Travel_Distance            0
DepartureDelay_in_Mins     0
ArrivalDelay_in_Mins       0
Seat_comfort               0
Seat_Class                 0
Arrival_time_convenient    0
Catering                   0
Platform_location          0
Onboardwifi_service        0
Onboard_entertainment      0
Online_support             0
Onlinebooking_Ease         0
Onboard_service            0
Leg_room                   0
Baggage_handling           0
Checkin_service            0
Cleanliness                0
Online_boarding            0
dtype: int64

In [23]:
for feature in df3.columns: 
    if df3[feature].dtype == 'object': 
        print('\n')
        print('feature:',feature)
        print(pd.Categorical(df3[feature].unique()))
        print(pd.Categorical(df3[feature].unique()).codes)
        df3[feature] = pd.Categorical(df3[feature]).codes



feature: Gender
[Female, Male, 0    Female\ndtype: object]
Categories (3, object): [0    Female\ndtype: object, Female, Male]
[1 2 0]


feature: CustomerType
[0    Loyal Customer\ndtype: object, disloyal Customer, Loyal Customer]
Categories (3, object): [0    Loyal Customer\ndtype: object, Loyal Customer, disloyal Customer]
[0 2 1]


feature: TypeTravel
[Business travel, Personal Travel, 0    Business travel\ndtype: object]
Categories (3, object): [0    Business travel\ndtype: object, Business travel, Personal Travel]
[1 2 0]


feature: Travel_Class
[Business, Eco]
Categories (2, object): [Business, Eco]
[0 1]


feature: Seat_comfort
[acceptable, extremely poor, excellent, poor, need improvement, good, 0    acceptable\ndtype: object]
Categories (7, object): [0    acceptable\ndtype: object, acceptable, excellent, extremely poor, good, need improvement, poor]
[1 3 2 6 5 4 0]


feature: Seat_Class
[Green Car, Ordinary]
Categories (2, object): [Green Car, Ordinary]
[0 1]


feature: Arriv

In [24]:
xtest = df3.drop(['ID'], axis =1)

In [ ]:
xtest = df3.drop(['ID','Overall_Experience'], axis =1)

In [25]:
xtest=xtest.apply(zscore)

In [ ]:
df3.head()

In [ ]:
df3['Overall_Experience'] = model3.predict(xtest)

In [ ]:
output = df3[['ID','Overall_Experience']]

In [ ]:
output.to_csv("Model3.csv",index=False)

<b>LDA<b>

In [ ]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn import metrics,model_selection
from sklearn.preprocessing import scale

In [ ]:
clf = LinearDiscriminantAnalysis()
model4=clf.fit(xtrain,ytrain)

In [ ]:
# Test Data Class Prediction with a cut-off value of 0.5
df3['Overall_Experience'] = model4.predict(xtest)

In [ ]:
output = df3[['ID','Overall_Experience']]
output.to_csv("Model4.csv",index=False)

<b>Random Forest <b>

In [ ]:
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestClassifier

param_grid = {
    'max_depth': [7, 8],
    'max_features': [11, 12, 13],
    'min_samples_leaf': [20, 25],
    'min_samples_split': [60, 75],
    'n_estimators': [101, 301]
}

rfcl = RandomForestClassifier()

grid_search = GridSearchCV(estimator = rfcl, param_grid = param_grid, cv = 3)



In [ ]:
grid_search.fit(xtrain, ytrain)

In [ ]:
grid_search.best_params_

In [ ]:
best_grid = grid_search.best_estimator_

In [ ]:
df3['Overall_Experience'] = best_grid.predict(xtest)

In [ ]:
output = df3[['ID','Overall_Experience']]
output.to_csv("Model5.csv",index=False)

# Decision tree

In [27]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.neural_network import MLPClassifier

In [ ]:
dt_model = DecisionTreeClassifier(criterion = 'gini' )

In [ ]:
dt_model.fit(xtrain, ytrain)

In [ ]:
from sklearn import tree

train_char_label = ['No', 'Yes']
HR_Tree_File = open('d:\hr_tree.dot','w')
dot_data = tree.export_graphviz(dt_model, out_file=HR_Tree_File, feature_names = list(xtrain), class_names = list(ytrain))

HR_Tree_File.close()

In [ ]:
from sklearn.model_selection import GridSearchCV

param_grid = {
    'max_depth': [5, 7, 8, 10],
    'min_samples_leaf': [15, 20, 25],
    'min_samples_split': [30, 45, 60]
}

dt_model = DecisionTreeClassifier()

grid_search = GridSearchCV(estimator = dt_model, param_grid = param_grid, cv = 3)

In [ ]:
grid_search.fit(xtrain, ytrain)

In [ ]:
grid_search.best_params_

In [ ]:
best_grid = grid_search.best_estimator_

In [ ]:
df3['Overall_Experience'] = best_grid.predict(xtest)

In [ ]:
output = df3[['ID','Overall_Experience']]
output.to_csv("Model6.csv",index=False)

# MLP

In [ ]:
from sklearn.preprocessing import StandardScaler 
sc = StandardScaler() 
xtrain = sc.fit_transform(xtrain) 
xtest = sc.transform (xtest)

In [29]:
from sklearn.model_selection import GridSearchCV

In [30]:
param_grid = {
    'hidden_layer_sizes': [(100,100,100,100)],
    'activation': ['logistic', 'relu'],
    'solver': ['sgd', 'adam'],
    'tol': [0.1,0.01,0.001,0.0001],
    'max_iter' : [10000]
}

rfcl = MLPClassifier()

grid_search = GridSearchCV(estimator = rfcl, param_grid = param_grid, cv = 3)

In [ ]:
grid_search.fit(xtrain, ytrain)

In [ ]:
grid_search.best_params_

In [ ]:
best_grid = grid_search.best_estimator_

In [ ]:
df3['Overall_Experience'] = best_grid.predict(xtest)

In [ ]:
output = df3[['ID','Overall_Experience']]
output.to_csv("Model7.csv",index=False)

# KNN

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

In [ ]:
NNH = KNeighborsClassifier(n_neighbors= 5 , weights = 'distance' )


In [ ]:
NNH.fit(xtrain, ytrain)

In [ ]:
df3['Overall_Experience'] = NNH.predict(xtest)

In [ ]:
output = df3[['ID','Overall_Experience']]
output.to_csv("Model8.csv",index=False)